from __future__ import annotations

SCHEMA_VERSION = "1.0"
EXTERNAL_POLICY_VERSION = "duplicate-policy-v1"
BODY_POLICY_VERSION = "content-jaccard-policy-v1"
CONTENT_NORMALIZATION_VERSION = "content-nfkc-ws-v1"
FINGERPRINT_VERSION = "char5-minhash128-lsh16x8-sha256-v1"
FINGERPRINT_ARTIFACT_VERSION = "fingerprint-artifact-v1"

EXPECTED_UNICODE_VERSION = "15.0.0"
MAX_CONTENT_BYTES = 5 * 1024 * 1024
MAX_UNIQUE_SHINGLES = 250_000
MAX_CANDIDATE_COUNT = 100
MAX_EXTERNAL_CANDIDATES = 10

SIGNATURE_WORDS = 128
SIGNATURE_BYTES = 1024
BAND_COUNT = 16
ROWS_PER_BAND = 8

POSSIBLE_NUMERATOR = 4
POSSIBLE_DENOMINATOR = 5
DUPLICATE_NUMERATOR = 23
DUPLICATE_DENOMINATOR = 25

GLOBAL_LOCK_NAME = "DEDUP_ADMISSION_GLOBAL"
SCHEMA_MIGRATION_VERSION = "001"

ALLOWED_MATCHED_BY = frozenset(
    {
        "CANONICAL_URL",
        "FINAL_URL",
        "CONTENT_HASH",
        "TITLE_SIMILARITY",
        "SOURCE_EXTERNAL_ID",
        "MANUAL_LINK",
    }
)
